name: Build MSM.Utility

on:
  - push

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        artifact:
          - MSM.Bot
          - MSM.TS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Install Dependencies
        run: dotnet restore

      - name: Build Release App
        run: >
          dotnet publish
          --configuration Release
          --runtime win-x64
          --self-contained
          --output ./build
          -p:PublishSingleFile=true
          ${{ matrix.artifact }}

      - name: Upload Artifact (${{ matrix.artifact }})
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: ./build/${{ matrix.artifact }}.*
