name: Build MSM.Utility.Bot

on:
  - push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Install dependencies
        run: dotnet restore

      - name: Build Release App
        run: >
          dotnet publish
          --configuration Release
          --runtime  win-x64
          --self-contained
          --output ./build
          -p:PublishSingleFile=true
          Mub.Main

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/MUB.Main.*
